//**************************** FuelPressure&Alarm ****************************** 
//  Copyright (c) 2026 Trenser Technology Solutions 
//  All Rights Reserved 
//****************************************************************************** 
// 
// File    : alarm.c
// Summary : File which contains function for triggering alarm when an event si- 
//           gnal is received. The alarm buzzer will be driven for 1s duration.
//           
// Note    : None
// Author  : Karthika V T
// Date    : 25-03-2026
// 
//******************************************************************************

//******************************* Include Files ********************************
#include "alarm.h"
#include "main.h"

//******************************* Local Types **********************************

//***************************** Local Constants ********************************

//***************************** Local Variables ********************************

//****************************** Local Functions *******************************

//****************************** FUNCTION_HEADER ******************************* 
//Purpose : This function is called by the siganl system call whenever a signal
//          is generated by the validation module. It can be configured to
//          trigger the alarm registers. 
//Inputs  : signal input from validation module
//Outputs : alarm can be triggered for defined time period
//Return  : None
//Notes   : None
//****************************************************************************** 
static void alarm_handler (int sig)
{
    printf ("Pressure alarm triggered\n");
}

//****************************** FUNCTION_HEADER ******************************* 
//Purpose : This function hardcode an arbitrary value for pressure and it is ma-
//          nipulated using rand() library function to get varying pressure val-
//          ue
//Inputs  : None
//Outputs : pressure value is calculated 
//Return  : unPressureVal - float value for pressure data
//Notes   : None
//****************************************************************************** 
void * alarmThread (void * arg)
{
    signal (SIGUSR1, alarm_handler);

    while (1)
    {
        pause ();
    }
    
    
}

// EOF